# Generated by Django 2.0.12 on 2020-06-30 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_public',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='movie',
            name='story_line',
            field=models.CharField(default='sdf', max_length=500),
        ),
    ]
