# Generated by Django 2.0.12 on 2020-06-30 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200630_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mean_rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
